services:
  server:
    build: ./server
    container_name: vitalink-server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build: ./client
    container_name: vitalink-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped
